title: Benri
description: We build tools that help people
baseurl: "/benri"
url: "https://rixgpt.github.io/benri"

theme: minima

# Blog settings
markdown: kramdown
permalink: /blog/:year/:month/:day/:title.html

# Plugins (for GitHub Pages)
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Exclude folders from the build
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
